// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7cVDfqlRSZyoOf0mQw1Miz8zsvP78rdw',
    appId: '1:556539587674:web:41f7829880dd3f5f36bc63',
    messagingSenderId: '556539587674',
    projectId: 'flutter-chat-app-a4d41',
    authDomain: 'flutter-chat-app-a4d41.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a4d41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuVZwJx7UY9izl77FNSBGqSL82jdai6g',
    appId: '1:556539587674:android:d4765f447a6e157136bc63',
    messagingSenderId: '556539587674',
    projectId: 'flutter-chat-app-a4d41',
    storageBucket: 'flutter-chat-app-a4d41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRV-Xoj973Xueh77D7kjt7RrprK6rJu1A',
    appId: '1:556539587674:ios:ce2060aa8d0b402436bc63',
    messagingSenderId: '556539587674',
    projectId: 'flutter-chat-app-a4d41',
    storageBucket: 'flutter-chat-app-a4d41.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRV-Xoj973Xueh77D7kjt7RrprK6rJu1A',
    appId: '1:556539587674:ios:ce2060aa8d0b402436bc63',
    messagingSenderId: '556539587674',
    projectId: 'flutter-chat-app-a4d41',
    storageBucket: 'flutter-chat-app-a4d41.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7cVDfqlRSZyoOf0mQw1Miz8zsvP78rdw',
    appId: '1:556539587674:web:b4839e2aae2750a536bc63',
    messagingSenderId: '556539587674',
    projectId: 'flutter-chat-app-a4d41',
    authDomain: 'flutter-chat-app-a4d41.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a4d41.appspot.com',
  );
}
